[package]
name = "zcash_client_sqlite"
description = "An SQLite-based Zcash light client"
version = "0.7.1"
authors = [
    "Jack Grigg <jack@z.cash>",
    "Kris Nuttycombe <kris@electriccoin.co>"
]
homepage = "https://github.com/zcash/librustzcash"
repository = "https://github.com/zcash/librustzcash"
readme = "README.md"
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.65"

[dependencies]
zcash_client_backend = { version = "=0.10.1", path = "../zcash_client_backend" }
zcash_encoding = { version = "0.2", path = "../components/zcash_encoding" }
zcash_primitives = { version = "=0.13.0-rc.1", path = "../zcash_primitives", default-features = false }

# Dependencies exposed in a public API:
# (Breaking upgrades to these require a breaking upgrade to this crate.)
# - Errors
bs58 = { version = "0.5", features = ["check"] }
hdwallet = { version = "0.4", optional = true }

# - Logging and metrics
tracing = "0.1"

# - Serialization
byteorder = "1"
prost = "0.12"
group = "0.13"
jubjub = "0.10"

# - Secret management
secrecy = "0.8"

# - Note commitment trees
incrementalmerkletree = "0.5"
shardtree = { version = "0.1", features = ["legacy-api"] }

# - SQLite databases
rusqlite = { version = "0.29.0", features = ["bundled", "time", "array"] }
schemer = "0.2"
schemer-rusqlite = "0.2.2"
time = "0.3.22"
uuid = "1.1"

# Dependencies used internally:
# (Breaking upgrades to these are usually backwards-compatible, but check MSRVs.)
maybe-rayon = {version = "0.1.0", default-features = false}

[dev-dependencies]
assert_matches = "1.5"
incrementalmerkletree = { version = "0.5", features = ["test-dependencies"] }
shardtree = { version = "0.1", features = ["legacy-api", "test-dependencies"] }
proptest = "1.0.0"
rand_core = "0.6"
regex = "1.4"
tempfile = "3.5.0"
zcash_note_encryption = "0.4"
zcash_proofs = { version = "=0.13.0-rc.1", path = "../zcash_proofs" }
zcash_primitives = { version = "=0.13.0-rc.1", path = "../zcash_primitives", features = ["test-dependencies"] }
zcash_client_backend = { version = "=0.10.1", path = "../zcash_client_backend", features = ["test-dependencies"] }
zcash_address = { version = "0.3.2", features = ["test-dependencies"] }

[features]
default = ["multicore"]
multicore = ["maybe-rayon/threads", "zcash_primitives/multicore"]
mainnet = []
test-dependencies = [
    "incrementalmerkletree/test-dependencies",
    "zcash_primitives/test-dependencies",
    "zcash_client_backend/test-dependencies",
    "incrementalmerkletree/test-dependencies",
]
transparent-inputs = ["hdwallet", "zcash_client_backend/transparent-inputs"]
unstable = ["zcash_client_backend/unstable"]

[lib]
bench = false
